version: '3.8'
services:

  employees-service:
    user: 10001:10001
    build: 
      context: ../
      dockerfile: ./deployment/Dockerfile.prod
    command:
      - -envflag=production
    env_file:
      - ../environment/production.env
    restart: always
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongodb-service
      
  mongodb-service:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./db-data/mongo/:/data/db/
    env_file:
      - ../environment/mongo.env
    ports:
      - 27017:27017
    restart: always
